/* empty css                      */(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const d of t.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&a(d)}).observe(document,{childList:!0,subtree:!0});function c(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=c(e);fetch(e.href,t)}})();document.addEventListener("DOMContentLoaded",()=>{const s=document.querySelector(".demo-btn"),n=document.querySelector(".iframe-wrapper"),c=document.getElementById("gameIframe"),a=document.getElementById("closeIframeBtn");!s||!c||!a||!n||(s.addEventListener("click",e=>{e.preventDefault(),c.src=s.dataset.gameUrl,c.classList.add("active"),n.classList.add("active"),a.classList.add("active"),s.style.display="none"}),a.addEventListener("click",()=>{c.src="",c.classList.remove("active"),n.classList.remove("active"),a.classList.remove("active"),s.style.display="block"}))});document.addEventListener("DOMContentLoaded",()=>{const s=document.querySelector(".menu-button"),n=s.querySelector(".icon"),c=document.querySelector(".modal"),a=document.querySelectorAll(".menu-list-item"),e=document.querySelector(".header");let t=!1;const d=`
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <rect x="0.5" y="0.5" width="23" height="23" rx="3.5" stroke="#F9DC23" />
  <path d="M5.625 7.125H18.375M5.625 16.125H18.375M5.625 11.625H18.375" stroke="#ECF3EC" stroke-linecap="round" />
</svg>
    `,o=`
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <rect x="0.5" y="0.5" width="23" height="23" rx="3.5" stroke="#F9DC23" />
  <path d="M5.25 5.25L12 12M12 12L5.25 18.75M12 12L18.75 18.75M12 12L18.75 5.25" stroke="#ECF3EC" stroke-linecap="round" stroke-linejoin="round" />
</svg>
    `;s.addEventListener("click",()=>{t=!t,n.innerHTML=t?o:d,t?r():i()}),a.forEach(u=>u.addEventListener("click",()=>{i(),n.innerHTML=d,t=!1})),window.addEventListener("scroll",l);function r(){c.style.display="block"}function i(){c.style.display="none"}function l(){e&&(window.scrollY>60?e.classList.add("header-scroll"):e.classList.remove("header-scroll"))}});document.addEventListener("DOMContentLoaded",()=>{function s(){const o=document.getElementById("site-header");return o?o.offsetHeight:0}function n(o){const r=document.getElementById(o);if(!r)return;const i=s(),l=r.getBoundingClientRect().top+window.pageYOffset-i;window.scrollTo({top:l,behavior:"smooth"})}document.querySelectorAll(".navigation-item a").forEach(o=>{o.addEventListener("click",function(r){const i=this.getAttribute("href");if(!i)return;const[l,u]=i.split("#");if(!u)return;const f=window.location.pathname.split("/").pop();!(l===""||l==="./"||l===f||l==="./"+f)||!document.getElementById(u)||(r.preventDefault(),n(u),t(u))})});const a=document.querySelectorAll("section[id]"),e=document.querySelectorAll(".navigation-item");function t(o){e.forEach(i=>i.classList.remove("active"));const r=document.querySelector(`.navigation-item a[href*="#${o}"]`);r&&r.closest(".navigation-item").classList.add("active")}function d(){const o=window.pageYOffset+s()+100;a.forEach(r=>{const i=r.offsetTop,l=i+r.offsetHeight;o>=i&&o<l&&t(r.id)})}if(window.addEventListener("scroll",d),window.location.hash){const o=window.location.hash.substring(1);setTimeout(()=>{n(o),t(o)},300)}});
//# sourceMappingURL=index.js.map
